version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: pm
      POSTGRES_PASSWORD: pm
      POSTGRES_DB: techmarket
    ports:
      - "5433:5432" # usa 5433 no host para evitar conflito
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pm -d techmarket"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: pm
      DB_PASSWORD: pm
      DB_NAME: techmarket
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/server

volumes:
  db_data:
